on:
  workflow_dispatch:
    inputs:
      upstream_branch:
        description: 'upstream_branch'
        required: true
        # default: 'master'
jobs:
  build-chain:
    runs-on: ubuntu-latest
    steps:
      - name: "echo inside this repo"
        run: |
          echo "echo inside dispatch DownStream";
          echo upstream branch ${{ inputs.upstream_branch }}
          sleep 10;
