on: [workflow_dispatch]
jobs:
  build-chain:
    runs-on: ubuntu-latest
    steps:
      - name: "echo inside this repo"
        run: |
          echo "echo inside dispatch DownStream";
          sleep 30;
