on:
  workflow_dispatch:
    inputs:
      upstream_branch:
        description: 'upstream_branch'
        required: false
        default: 'master'
jobs:
  build-chain:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          repository: wuisky/try-dispatch
          ref:  ${{ inputs.upstream_branch }}
      - name: "echo inside this repo"
        run: |
          ls;
          echo "echo inside dispatch DownStream";
          echo upstream branch ${{ inputs.upstream_branch }}
          sleep 10;
